# Generated by Django 2.2.9 on 2021-04-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名称')),
                ('host', models.GenericIPAddressField(protocol='IPv4', verbose_name='主机')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '环境信息',
                'verbose_name_plural': '环境信息',
            },
        ),
    ]
