# Generated by Django 2.2.9 on 2021-04-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envinfo',
            name='port',
            field=models.CharField(default=1, max_length=6, verbose_name='端口'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='命令名称')),
                ('command', models.CharField(max_length=100, verbose_name='执行命令')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('envtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.EnvInfo', verbose_name='环境类型')),
            ],
            options={
                'verbose_name': '命令信息',
                'verbose_name_plural': '命令信息',
            },
        ),
    ]
