# Generated by Django 2.2.9 on 2021-04-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210415_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cominfo',
            name='envtype',
        ),
    ]
