# Generated by Django 2.2.9 on 2021-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_cominfo_envtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envinfo',
            name='host',
        ),
        migrations.RemoveField(
            model_name='envinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='envinfo',
            name='port',
        ),
        migrations.RemoveField(
            model_name='envinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='envinfo',
            name='envinfo',
            field=models.CharField(default=1, max_length=100, verbose_name='环境信息'),
            preserve_default=False,
        ),
    ]
