# Generated by Django 2.2.9 on 2021-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20210415_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='envinfo',
            field=models.CharField(max_length=300, verbose_name='环境信息'),
        ),
    ]
