# Generated by Django 2.2.9 on 2021-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20210415_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envinfo',
            old_name='envinfo',
            new_name='info',
        ),
        migrations.AddField(
            model_name='envinfo',
            name='ident',
            field=models.CharField(default=1, max_length=20, verbose_name='标识'),
            preserve_default=False,
        ),
    ]
