# Generated by Django 2.2.9 on 2021-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20210415_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='ident',
            field=models.CharField(max_length=20, verbose_name='唯一标识'),
        ),
    ]
