# Generated by Django 2.2.9 on 2021-04-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20210415_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cominfo',
            name='ident',
            field=models.CharField(default=1, max_length=20, verbose_name='唯一标识'),
            preserve_default=False,
        ),
    ]
