# Generated by Django 2.2.9 on 2022-01-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_cominfo_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='command',
            field=models.CharField(max_length=200, verbose_name='执行命令'),
        ),
    ]
