# Generated by Django 2.2.9 on 2022-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delay',
            field=models.IntegerField(choices=[(0, '是'), (1, '否')], default=1, verbose_name='延期'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
