# Generated by Django 2.2.9 on 2022-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220208_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
