# Generated by Django 2.2.9 on 2022-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delay',
            field=models.IntegerField(choices=[(0, '是'), (1, '否')], default=1, verbose_name='延期'),
        ),
    ]
