# Generated by Django 2.2.9 on 2022-02-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='percent',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AddField(
            model_name='record',
            name='path',
            field=models.CharField(default=11, max_length=30, verbose_name='访问地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pinyin',
            field=models.CharField(default=11, max_length=20, verbose_name='拼音名'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('H', '工时'), ('B', 'BUG')], default='H', max_length=5, verbose_name='类型')),
                ('tester', models.CharField(max_length=5, verbose_name='姓名')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('desc', models.CharField(blank=True, max_length=50, verbose_name='描述')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Hours', verbose_name='月份')),
            ],
            options={
                'verbose_name': '个人积分',
                'verbose_name_plural': '个人积分',
            },
        ),
    ]
