# Generated by Django 2.2.9 on 2022-08-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220302_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='app',
            field=models.CharField(blank=True, default='N/A', max_length=10, verbose_name='app版本号'),
        ),
    ]
