# Generated by Django 2.2.9 on 2022-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_percent_ident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=5, verbose_name='姓名')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('desc', models.CharField(blank=True, max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '个人积分',
                'verbose_name_plural': '个人积分',
            },
        ),
        migrations.AddField(
            model_name='percent',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
    ]
