# Generated by Django 2.2.9 on 2022-02-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220218_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Hours', verbose_name='月份'),
            preserve_default=False,
        ),
    ]
