# Generated by Django 2.2.9 on 2022-02-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_score_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date',
            new_name='month',
        ),
    ]
