# Generated by Django 2.2.9 on 2022-02-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20220218_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='path',
            field=models.CharField(default=1, max_length=30, verbose_name='访问地址'),
            preserve_default=False,
        ),
    ]
